project:
  type: website

website:
  title: "skeptric"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/EdwardJRoss
format:
  html:
    theme: cosmo
    css: styles.css

freeze: true
