baseURL = "https://skeptric.com/"
languageCode = "en-us"
theme = "hugo-casper3"
paginate = 12
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title = "Skeptric"
  subtitle = "by Edward Ross"

  cover = "images/dumbjump.png"
  description = "Learning about the world through critical thinking, data and programming."
  customCSS = ["css/custom.css"]
  RSSLink = ""

  twitterName = "EddingtonRoss"
  linkedinName = "edward-ross-4909ba13a"


  githubName = "edwardjross"
  #logo = "favicon.ico"
  orgName = "Skeptric"
  orgWebsite = "https://www.skeptric.com"
  orgDescription = ""

  author = "Edward Ross"
  authorAvatar = "images/edwardjross.jpg"

  pageNotFoundTitle = "404 - Page not found"

  singleViewStyle = "casper"

[permalinks]
  post = "/:filename/"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 200

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 100
